DROP TABLE IF EXISTS ABONNEE;
CREATE TABLE ABONNEE(
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  wachtwoord VARCHAR(50) NOT NULL,
  ingelogd BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS CATEGORIE;
CREATE TABLE CATEGORIE(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  titel VARCHAR(50) NOT NULL,
  maandprijs DECIMAL(10,2) NOT NULL
);

DROP TABLE IF EXISTS ABONNEE_CATEGORIE;
CREATE TABLE ABONNEE_CATEGORIE(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  abonnee_id INT NOT NULL,
  categorie_id INT NOT NULL,
  prijs DECIMAL(10,2) NOT NULL,
  start_datum DATE,
  eind_datum DATE
);